services:
  pg2minio:
    build:
      context: ./dump
    env_file:
      - .env.dev
    depends_on:
      minio:
        condition: service_healthy
      pg:
        condition: service_healthy
  restore:
    build:
      context: ./restore
    env_file:
      - .env.dev
    depends_on:
      pg:
        condition: service_healthy
      minio:
        condition: service_healthy
  pg:
    image: postgres:16
    env_file:
      - .env.dev
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio
    env_file:
      - .env.dev
    command: server /data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
